version: '3'

services:
  consul:
    image: hashicorp/consul:1.19
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    networks:
      - miage24

  keycloak_db:
    image: postgres
    environment:
      - POSTGRES_USER=miage24
      - POSTGRES_PASSWORD=tagada54
      - POSTGRES_DB=miage24
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - miage24

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: start
    environment:
      #KC_HOSTNAME: localhost
      #KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT_BACKCHANNEL: false
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HEALTH_ENABLED: true
      KC_FEATURES: token-exchange
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: tagada54
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/miage24
      KC_DB_USERNAME: miage24
      KC_DB_PASSWORD: tagada54
    restart: always
    depends_on:
      - keycloak_db
    networks:
      - miage24

  traefik:
    image: traefik:v3.3
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - miage24

networks:
  stack:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/24

volumes:
  postgres-data:
