global:
  checkNewVersion: false
  sendAnonymousUsage: false

entryPoints:
  web:
    address: :80

  websecure:
    address: :443

api:
  insecure: true
  dashboard: true

providers:
  consulCatalog:
    namespace: "miage24"
    defaultRule: "Host(`{{ .Name }}.mbyte.dev.local`)"
    endpoint:
      address: "<hcp-consul-address>"
      scheme: http
      token: <hcp-consul-token>

  consul:
    namespace: "traefik"
    rootKey: "traefik"
    token: <hcp-consul-token>
    endpoints:
      - "http://<hcp-consul-address>"
